<?php

use Illuminate\Database\Seeder;

class TermsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('terms')->insert([
            'name' => 'First Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => '2018-12-05 13:20:06',
            'created_at' => '2017-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'Second Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => '2018-12-16 13:20:06',
            'created_at' => '2017-11-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'Third Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => '2020-01-01 13:20:06',
            'created_at' => '2017-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'Fourth Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => '2020-02-05 13:20:06',
            'created_at' => '2017-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'Fifth Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => null,
            'created_at' => '2019-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'asd Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => null,
            'created_at' => '2019-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'asdf Terms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => null,
            'created_at' => '2019-12-05 13:20:06'
        ]);
        DB::table('terms')->insert([
            'name' => 'asdfgTerms',
            'content' => 'This website is provided as a public service. No warranty or guarantee is provided pertaining to the quality of data or service. By accepting this agreement, you assume full responsibility for any misuse of the information provided to you.\nAll generated credit card numbers are fictional. While they will pass a basic validation check, they will not work to purchase anything. Corban Works cannot and will not provide real credit card numbers. You acknowledge that attempting to use these credit card numbers for anything other than testing or training purposes is fraud.Screen scraping is not permitted. If you need automated access to our data, please apply for an API key.In addition, by accepting this agreement you also indemnify and hold harmless Corban Works, its employees, agents, officers, affiliates, and host from any claims, costs, damages, or expenses resulting from injury, damage, loss, or legal action that may result from the use of the provided information.By accepting this agreement you acknowledge that the information provided is randomly generated, and should be considered fictional. Any similarities between generated identities and actual person(s) is completely coincidental.You agree to be bound by our license agreement.Customers may place as many free orders as they want, but are only allowed to have three (3) free orders in the queue at a time. We do not accept orders from customers using throw-away email addresses (Mailinator, Spambob, etc.) or email addresses with trusted delivery systems (Bluebottle, etc.). We reserve the right to cancel any order at any time for any reason with or without notice.',
            'published_at' => null,
            'created_at' => '2019-12-05 13:20:06'
        ]);
    }
}
